List searches = [
    "Most addictive Games",
    "Offline Games",
    "Most popular Games",
    "Most popular Games for PC",
    "Most popular Games for Android",
    "Most popular Games of all time",
    "Top PvP games",
    "Most popular Games for xbox",
    "Most popular Games for PS5",
    "Can we run GTA 5 on xbox",
    "Is GTA 5 is available on Xbox game pass",
    "Red dead is better then GTA V",
    "Play Epic games on Xbox",
    "Play steam games on Xbox",
    "Best Naruto games of all time",
    "Top anime this year",
    "Top anime last year",
    "Top completed anime",
    "Top newly completed Anime",
    "New games this year",
    "MMO RPG games for PC",
    "Best MMO RPG games",
    'Latest anime releases',
    'Popular anime series and their reviews',
    'Latest open-source projects and releases',
    'Contributions to open-source projects',
    'Telegram updates and features',
    'Telegram bots and channels',
    'Cloud storage providers and their features',
    'Popular games and their reviews',
    'Upcoming games and their announcements',
    'Telegram API documentation and tutorials',
    'Telegram API use cases and examples',
    'Telegram API integrations with other technologies',
    'Telegram API tools and libraries',
    'Telegram API-powered projects and apps',
    'Telegram API tools and libraries',
    'Telegram API-powered projects and apps',
    'Most addictive Games',
    'Offline Games',
    'Most popular Games',
    'Most popular Games for PC',
    'Most popular Games for Android',
    'Most popular Games of all time',
    'Top PvP games',
    'Most popular Games for xbox',
    'Most popular Games for PS5',
    'Can we run GTA 5 on xbox',
    'Is GTA 5 is available on Xbox game pass',
    'Red dead is better then GTA V',
    'Play Epic games on Xbox',
    'Play steam games on Xbox',
    'Best Naruto games of all time',
    'Top anime this year',
    'Top anime last year',
    'Top completed anime',
    'Top newly completed Anime',
    'New games this year',
    'MMO RPG games for PC',
    'Best MMO RPG games'
  ];
